### ISSUE TITLE
Support for extracting attributes from the root node

### ISSUE THREAD

**Issue by prewk** [prewk/xml-string-streamer#34]
````xml
<foo a="b">
  <bar>
  </bar>
  <bar>
  </bar>
</foo>
````

Extract `<foo a="b">` somehow

**Comment by jcrawford** [comment]
Ah I just shot you over an email about this asking if it was possible, hadn't seen this before now.  This would be really handy as I need to use that ability for one of the processes in my application.

**Comment by prewk** [comment]
Hm uh yeah, this seems to be the most frequently requested (twice!) feature so maybe I should try to look closer into it. It's been a while since I've done some work on this package :)

**Comment by jcrawford** [comment]
lmao yea I can't imagine the project gets that many requests as of yet but that is a pretty necessary feature for a lot of use cases :)

**Comment by prewk** [comment]
Btw, if you need that extracted right now I'd recommend you to extract it with regexp using some kind of CLI tool, like `awk` or just plain ole `grep`/`egrep` etc. With PHP's `exec` or something. I've used similar ugly techniques when needed :)

**Comment by prewk** [comment]
Alright, I've pushed a new minor version with support for extracting the containing XML. Haven't put it in the README yet. Usage, with your problem as example:

````php
<?php
// file.xml contains "<Catalog LastUpdate='4/13/2015 8:28:21 PM'><Item>....</Item><Item>....</Item></Catalog>"

use Prewk\XmlStringStreamer\Parser\StringWalker;
use Prewk\XmlStringStreamer\Stream\File;

$stream = new File("file.xml", 16384);
$parser = new StringWalker(array(
    "extractContainer" => true,
));
$streamer = new XmlStringStreamer($parser, $stream);

while ($node = $streamer->getNode()) {
    // Do something with the nodes, you have to go through them
}

// Now, afterwards, use getExtractedContainer() to get the containing XML
$containingXml = $streamer->getExtractedContainer();

// $containingXml should now be "<Catalog LastUpdate='4/13/2015 8:28:21 PM'></Catalog>"

$obj = simplexml_load_str($containingXml);

// And voilà:
$lastUpdate = $obj->attributes()->LastUpdate;
````

**Comment by jcrawford** [comment]
Awesome thank you, I will attempt to implement this later on today and let you know if i find any issues :)
