### ISSUE TITLE
Memory leak when starting tag not found

### ISSUE THREAD

**Issue by atompie** [prewk/xml-string-streamer#44]
First of all thanks for the great lib.

I found an error that make your lib leak memory when it does not find any of the defined uniqueNode.
I have a huge XML that may change. I defined opening tag to be X and everything works great. Memory usage is around 50 KB. When the XML changed and tag X does not exist any more the library starts to consume a lot of memory (XML has 110 MB).  

I checked the code and it seems that in the scenario when there is no node found the whole xml is loaded into memory.

Is there any chance to correct this. 

Thanks in advance.

**Comment by prewk** [comment]
Hi!

Hm, that's an interesting scenario. I'll have to look into it. You're not using `extractContainer`, right?

**Comment by atompie** [comment]
This is the code I am using:

```
 $streamer = XmlStringStreamer::createUniqueNodeParser($sUrl, array("uniqueNode" => "item"));
        while ($node = $streamer->getNode()) {
            $simpleXmlNode = simplexml_load_string($node);
            yield $simpleXmlNode;
        }
```

**Comment by prewk** [comment]
Should be sorted out in `0.7.3` I just released. Please try it out and get back to me on whether it solves your problem!

**Comment by atompie** [comment]
Thanks it works perfectly :)
