### ISSUE TITLE
UniqueNode Streamer Depth

### ISSUE THREAD

**Issue by lo3ty** [prewk/xml-string-streamer#48]
Hi,

is there any way to use the UniqueNode Streamer to get Nodes which aren't directly under the root?

For example process only all Nodes "B" in such kind of structure:
root
- child1
-- child 2
--- A
--- B
--- B
--- B
...

Documentation is not very specific on the usage of the UniqueNode Streamer..

Leonhard

**Comment by prewk** [comment]
Hi!

Does the node name you want have a specific unique name? In that case you just use that name instead in the options array: `"uniqueNode" => "your_child_node"`

If it's not unique, you'll have to use the `StringWalker` parser instead where you just specify depth, and not the name of the node.

To give you more specific help I'd need to see an example of your xml structure.

**Comment by prewk** [comment]
Please re-open if needed.
