### ISSUE TITLE
getNode() hangs on empty response

### ISSUE THREAD

**Issue by ronnievisser** [prewk/xml-string-streamer#49]
Hi,

I'm using the package together with the guzzle parser.I have to load a bunch of xml files into a local database and sometimes i'm getting an empty xml response from the remote server.

when calling the $parser->getNode() method it seems to be hanging since it's cant find the node (uniqueNodeParser).

I can see on the parser class there is a firstNodeFound property but I'm unable to access it.

if there a way to check if there are results without calling the getNode() method?

**Comment by ronnievisser** [comment]
I just saw that the firstNodeFound property is always false. even as the node is available

**Comment by prewk** [comment]
Is it reproducable by running the Unique Node Parser on an empty document? Or does it get stuck with Guzzle?

**Comment by ronnievisser** [comment]
yes, it's reproducable with the file streamer

**Comment by prewk** [comment]
Great, I'll take a look as soon as I find the time. Thanks for reporting!

Until then, you should probably only run it if you've gotten any XML.

**Comment by ronnievisser** [comment]
That's a bit difficult. I don't know on forehand.

but untill you got it fixed I will use my fork

**Comment by prewk** [comment]
I just released a new version `0.9.0` that should solve the problem. I bumped the minor because the change _might_ trigger some problems for some extremely weird edge cases.

**Comment by ronnievisser** [comment]
thanks, much appreciated

**Comment by ronnievisser** [comment]
can you update the dependency of the guzzle package to this one also?

**Comment by prewk** [comment]
Ah, yep. I curse the day I chose to split it up into its own repo..

I've released `0.2.0` there with this package's `0.9.0` as requirement.

If you want better control over the Guzzle version and stuff you might want to check out the only, simple, file that the `xml-string-streamer-guzzle` package actually consists of: https://github.com/prewk/xml-string-streamer-guzzle/blob/master/src/XmlStringStreamer/Stream/Guzzle.php

**Comment by ronnievisser** [comment]
Haha, thanks man!

Regards
