### ISSUE TITLE
Cannot rewind StreamInterface

### ISSUE THREAD

**Issue by vaclavvanik** [prewk/xml-string-streamer#66]
StreamInterface does not have ability to rewind stream. It causes that stream cannot  be parsed more than once.

**Comment by prewk** [comment]
True, sounds valid. Would having this help you use the package?

**Comment by vaclavvanik** [comment]
This feature would be great. Today I tried this library. Sadly a need to parse stream more than once and I figured it cannot be easily done :-/

Personally I would add two methods to `StreamInterface` - `isSeekable() : bool` and `rewind() : void`.
As in PSR-7. Example in [Diactoros](https://github.com/zendframework/zend-diactoros/blob/master/src/Stream.php#L168).

**Comment by prewk** [comment]
It's a good feature request. This library is a bit old and I have very little time at the moment, so I can't promise anything. Sounds like pretty easy to implement tho, rewinding should just clear some data and put whatever stateful "pointer" (depending on streamer) is in place back to the beginning.

**Comment by vaclavvanik** [comment]
Just simple untested php ^5.3 implementation:

```php
<?php namespace Prewk\XmlStringStreamer\Stream;

use Prewk\XmlStringStreamer\StreamInterface;

class File implements StreamInterface
{
...
    public function isSeekable() /*: bool*/
    {
        $meta = stream_get_meta_data($this->handle);
        return $meta['seekable'];
    }

    public function rewind() /*: void*/
    {
	if (! $this->isSeekable()) {
            throw new \Exception('Stream is not seekable');
        }

        $this->readBytes = 0;
        rewind($this->handle);
    }
}
```
StreamInterface has to be extended too.

**Comment by prewk** [comment]
@vaclavvanik check this out and lemme know what you think https://github.com/prewk/xml-string-streamer/pull/67
