### ISSUE TITLE
Imposssible (how to?) access parent node

### ISSUE THREAD

**Issue by tuttiflirty** [prewk/xml-string-streamer#68]
If I set the capture depth to 4 for instance, and the nodes of depth 3 are not parsed (not shown in ` while ($node = $streamer->getNode()) { // depth 3 nodes not shown }`). I'd like to produce a csv like file from xml but I can find how to "link" the depths in between. Any suggestions please ?

**Comment by prewk** [comment]
Hm, well one of the "foundations" of the library is to throw away as much data as possible that's not wanted to be memory efficient, so it's working as intended if it's only capturing depth 4 if you specify depth 4.

It won't be able to find the parent for you, because it's just skipped unless you set it to depth 3.

I assume you can't use depth 3 because it's too large, or..?

**Comment by tuttiflirty** [comment]
I can use depth 3 but obviously there are not child nodes. How can I join
children nodes with parent nodes following the xml hierarchy  ? Cause my
child nodes do not contain any reference (such as id) to depth 3 parent
node..

Thank you !

Le mer. 20 mai 2020 à 19:30, Oskar Thornblad <notifications@github.com> a
écrit :

**Comment by prewk** [comment]
Sorry, I don't follow.

Depth 3 contains depth 3 and everything below.

```xml
<depth_1>
  <depth_2>
    <depth_3>
      <depth_4>
        Lorem
      </depth_4>
      <depth_4>
         Ipsum
      </depth_4>
    </depth_3>
  </depth_2>
</depth_1>
```

☝️ Capturing depth 4 here iterates **twice** and captures:

1.

```xml
      <depth_4>
        Lorem
      </depth_4>
```

2.

```xml
      <depth_4>
        Ipsum
      </depth_4>
```

Capturing depth **3** iterates **once** and captures:

```xml
    <depth_3>
      <depth_4>
        Lorem
      </depth_4>
      <depth_4>
         Ipsum
      </depth_4>
    </depth_3>
```

That is - depth 3 contains both depth 3 and everything below (eg. depth 4)

**Comment by tuttiflirty** [comment]
Thank you :)

**Comment by prewk** [comment]
Oh ok :D glad I could help!

ons 20 maj 2020 kl. 20:56 skrev Tutti flirty <notifications@github.com>:
