### ISSUE TITLE
AWS S3 stream wrapper support

### ISSUE THREAD

**Issue by bs-thomas** [prewk/xml-string-streamer#82]
It seems like s3 is not a part of the common stream/URL wrappers in the File.php code.

Would it be possible to add that in?  (I could imagine it would be nice to parametize that later on, but I'm a schedule for a project.  Can we support this?  I can send in a pull request shortly.)

![image](https://user-images.githubusercontent.com/2464920/221586459-011f2596-6de6-439c-98b9-a13c04e0c5fd.png)

Thank you very much!

**Comment by prewk** [comment]
That particular code has to do with this change: https://github.com/prewk/xml-string-streamer/pull/76

It's for being able to use PHP's built-in support for certain protocols.

S3 isn't a "protocol", it's a product (if you know what I mean).

What you need is Guzzle: https://github.com/prewk/xml-string-streamer-guzzle

**Comment by bs-thomas** [comment]
Actually I can understand that S3 isn't a protocol itself, but the magic behind this is that S3 can be treated like a file system seamlessly, and work with many libraries natively regardless of its age.

In fact my file is private, and cannot be access "through the normal routine" via Guzzle because there is some complicated authentication behind it.

You probably know that almost all cloud service providers nowadays have a fallback S3 protocol support in terms of storage (eg. Azure, Google Cloud, Alibaba Cloud, and a lot more out there).  It really acts like a standardized protocol nowadays.

I could imagine that a more ideal modification to this library would be to parametize this, such that it can be supported with flexibility (instead of hardcoding in there).

I was just on a project schedule where this needs to be supported somehow.

Would there be any mercy at this point to allow me this patch in?  I plan to parametize it.
Or if not, can you allow me to parametize this right now so that s3 will work?
I'm sure it will be a convenient upgrade for many users out there, as cloud storage is the norm now.

Hope we can somehow get to a point that would work out nicely.

Thank you very much once again.

**Comment by bs-thomas** [comment]
I can make use of your $options parameter for this.  Would that be a fair upgrade?  It's an added flexibility.

**Comment by prewk** [comment]
>Actually I can understand that S3 isn't a protocol itself, but the magic behind this is that S3 can be treated like a file system seamlessly, and work with many libraries natively regardless of its age.

Did a quick google and found this: https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html

Is that what you're using?

>In fact my file is private, and cannot be access "through the normal routine" via Guzzle because there is some complicated authentication behind it.

Alright, I would assume that the Guzzle AWS client would solve it but maybe it's got some weirdness :)

I guess "anything" could be allowed for the url wrappers etc in reality.

I'm out of touch with the PHP ecosystem so I don't wanna screw around too much with this package in case of breakage. I'd advice you to copy paste https://github.com/prewk/xml-string-streamer/blob/master/src/XmlStringStreamer/Stream/File.php and change it to your own class.

In the readme, look under `Without the convenience method (functionally equivalient):` and you'll see how to use your own stream class instead. That would solve the problem for you without any hacks, yes?

**Comment by bs-thomas** [comment]
This is a very small tweak.  Backwards compatible, and extra feature.

I just saw your message now, I will also see the "Wtihout the convenience method" too though.  I just felt like this was something I could do for the community too.

Hope you can take a look at the code, and let me know what you think.  It's nothing complicated.  And I used "older syntax" too to ensure old PHP versions still continue to work.

**Comment by bs-thomas** [comment]
I see what you mean by the "Without the convenience method" now.  I can just duplicate the file stream, make the tweaks, and initialize it using my own stream class that follows the stream interface.

That will definitely work, but I just need to maintain my own copy of the stream wrapper as an outlier.

I guess you can see if my upgrade is acceptable first?  That is the ideal option, and a great upgrade to attract cloud storage developers.

If really for whatever reason it doesn't work for you, then I'll fallback to the "inconvenient" option?

Please let me know.  Thank you very much, once again!!

**Comment by bs-thomas** [comment]
Sorry I forgot to reply you on this question.

> > Actually I can understand that S3 isn't a protocol itself, but the magic behind this is that S3 can be treated like a file system seamlessly, and work with many libraries natively regardless of its age.
> 
> Did a quick google and found this: https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html
> 
> Is that what you're using?
Yes that's why I'm using.

**Comment by bs-thomas** [comment]
@prewk Hello there, really apologies for chasing you here, but I was ust wondering if you have had a chance to review my PR?

May I ask if you would be able to merge it in?  I'd have to make a decision so we can continue with the development.

Once again, thank you very much for the time!

**Comment by prewk** [comment]
I'm not sure I want to merge it, the `File` stream is supposed to support stuff from here: https://www.php.net/manual/en/wrappers.php

But you have a working solution, the `File` thing from this lib is for convenience, it's easy to provide your own.

If you make a PR that changes `File` to not file_exists-check anything with a protocol (starting with `[a-z]+://`) I'm more inclined to allow it.

**Comment by bs-thomas** [comment]
Understood.  That code is pretty much there, it's just routing to strip the protocol part when it doesn't find a matching one right now.

Let me do a PR shortly.  It's an easy change.

Thank you very much buddy!

**Comment by bs-thomas** [comment]
@prewk  Can you please see if this pull request addresses your advice?

Thank you very much once again!
