### ISSUE TITLE
Library not reading all xml

### ISSUE THREAD

**Issue by tuliofindi** [prewk/xml-string-streamer#86]
Library not reading all xml

I loved the library, it's meeting my needs. But my application still can't read all the xml.

At some point it is interrupted.

I already tried to understand the solution of this similar problem https://github.com/prewk/xml-string-streamer/issues/81. But without success.

Someone with the same problem?

**Comment by tuliofindi** [comment]
> Library not reading all xml
> 
> I loved the library, it's meeting my needs. But my application still can't read all the xml.
> 
> At some point it is interrupted.
> 
> I already tried to understand the solution of this similar problem #81. But without success.
> 
> Someone with the same problem?

/

**Comment by prewk** [comment]
Can you provide an XML that does this?

**Comment by prewk** [comment]
Oh, you closed it. Solved?

**Comment by tuliofindi** [comment]
Sorry, it was a little problem in my own application, but I already solved it.

The Library is working 100%
